"""Inference pipeline script generation for SWE-Lego.

Generates shell scripts for vLLM serving, OpenHands agent inference,
and SWE-bench evaluation.
"""

from __future__ import annotations

import shlex
from pathlib import Path

SWE_LEGO_ROOT = Path(__file__).parent / "SWE-Lego"


def _shell_quote(value: str) -> str:
    """Quote a value for shell embedding, but pass through shell variable references as-is."""
    if value.startswith("$") or value.startswith("${"):
        return value
    return shlex.quote(value)


def build_serve_script(
    checkpoint_path: str,
    bundle_dir: str | Path,
    tp_size: int = 1,
    port: int = 8000,
    gpu_memory_utilization: float = 0.9,
    max_model_len: int = 163840,
    vllm_extra_flags: list[str] | None = None,
) -> str:
    """Generate vLLM model serving script.

    Based on SWE-Lego/scripts/swe_lego_qwen3_8b/serve_vllm.sh.

    Returns script content string.
    """
    bundle_dir = Path(bundle_dir)
    extra_flags = ""
    if vllm_extra_flags:
        extra_flags = " \\\n    " + " \\\n    ".join(vllm_extra_flags)
    return f"""\
#!/usr/bin/env bash
set -euo pipefail

# vLLM serving script — generated by auto-coder-trainer
# Checkpoint: {checkpoint_path}

CHECKPOINT_PATH={_shell_quote(checkpoint_path)}
PORT={port}

python -m vllm.entrypoints.openai.api_server \\
    --model "$CHECKPOINT_PATH" \\
    --served-model-name "$CHECKPOINT_PATH" \\
    --host 0.0.0.0 \\
    --port "$PORT" \\
    --tensor-parallel-size {tp_size} \\
    --gpu-memory-utilization {gpu_memory_utilization} \\
    --max-model-len {max_model_len} \\
    --max-num-seqs 24 \\
    --api-key "dummy-key"{extra_flags}
"""


def build_infer_script(
    bundle_dir: str | Path,
    model_name: str = "Qwen/Qwen3-8B",
    port: int = 8000,
    num_workers: int = 1,
    max_iterations: int = 100,
    eval_limit: int = 500,
    dataset: str = "princeton-nlp/SWE-bench_Verified",
    openhands_model_config: str = "llm.eval_qwen3_8b",
) -> str:
    """Generate OpenHands agent inference script.

    Based on SWE-Lego/scripts/swe_lego_qwen3_8b/infer.sh.
    Uses the OpenHands installed at SWE-Lego/OpenHands-0.53.0/.

    Returns script content string.
    """
    bundle_dir = Path(bundle_dir)
    swe_lego_root = "${ACT_SWE_LEGO_ROOT:-" + shlex.quote(str(SWE_LEGO_ROOT)) + "}"
    return f"""\
#!/usr/bin/env bash
set -euo pipefail

# OpenHands agent inference script — generated by auto-coder-trainer

SWE_LEGO_ROOT={swe_lego_root}
cd "$SWE_LEGO_ROOT/OpenHands-0.53.0"

MODEL_CONFIG={openhands_model_config}
GIT_VERSION=HEAD
AGENT=CodeActAgent
EVAL_LIMIT={eval_limit}
MAX_ITER={max_iterations}
NUM_WORKERS={num_workers}
DATASET={shlex.quote(dataset)}
DATASET_SPLIT=test
N_RUNS=1
MODE=swe

export USE_HINT_TEXT=false
export INSTRUCTION_TEMPLATE_NAME=swe_default.j2
export ENABLE_PLAN_MODE=false
export ADD_IN_CONTEXT_LEARNING_EXAMPLE=false

./evaluation/benchmarks/swe_bench/scripts/run_infer.sh \\
    "$MODEL_CONFIG" "$GIT_VERSION" "$AGENT" "$EVAL_LIMIT" \\
    "$MAX_ITER" "$NUM_WORKERS" "$DATASET" "$DATASET_SPLIT" \\
    "$N_RUNS" "$MODE"
"""


def build_eval_script(
    bundle_dir: str | Path,
    output_jsonl: str = "",
    dataset: str = "princeton-nlp/SWE-bench_Verified",
    model_short_name: str = "",
    max_iterations: int = 100,
) -> str:
    """Generate SWE-bench evaluation script.

    Based on SWE-Lego/scripts/swe_lego_qwen3_8b/eval.sh.
    Two stages: OpenHands output conversion + SWE-bench harness evaluation.

    Returns script content string.
    """
    bundle_dir = Path(bundle_dir)
    swe_lego_root = "${ACT_SWE_LEGO_ROOT:-" + shlex.quote(str(SWE_LEGO_ROOT)) + "}"

    if not output_jsonl:
        short = model_short_name or "Qwen3-8B"
        output_jsonl = (
            "evaluation/evaluation_outputs/outputs/"
            "princeton-nlp__SWE-bench_Verified-test/"
            f"CodeActAgent/{short}_maxiter_{max_iterations}_N_v0.53.0-no-hint-noplan-run_1/output.jsonl"
        )

    return f"""\
#!/usr/bin/env bash
set -euo pipefail

# SWE-bench evaluation script — generated by auto-coder-trainer

SWE_LEGO_ROOT={swe_lego_root}
DATASET={shlex.quote(dataset)}
DATASET_SPLIT=test

# Stage 1: Convert OpenHands output
YOUR_OUTPUT_JSONL={shlex.quote(output_jsonl)}

cd "$SWE_LEGO_ROOT/OpenHands-0.53.0"
./evaluation/benchmarks/swe_bench/scripts/eval_infer.sh \\
    "$YOUR_OUTPUT_JSONL" \\
    dataset_name="$DATASET" split="$DATASET_SPLIT" --convert-only

# Stage 2: SWE-bench harness evaluation
cd "$SWE_LEGO_ROOT/SWE-bench-4.0.4"

SWEBENCH_JSONL="../OpenHands-0.53.0/${{YOUR_OUTPUT_JSONL/output.jsonl/output.swebench.jsonl}}"

python -m swebench.harness.run_evaluation \\
    --max_workers 10 \\
    --dataset_name "$DATASET" \\
    --report_dir ./results/ \\
    --cache_level instance \\
    --predictions_path "$SWEBENCH_JSONL" \\
    --run_id openhands \\
    --timeout 500
"""


def build_serve_and_infer_script(
    checkpoint_path: str,
    bundle_dir: str | Path,
    tp_size: int = 1,
    port: int = 8000,
    gpu_memory_utilization: float = 0.9,
    max_model_len: int = 163840,
    model_name: str = "Qwen/Qwen3-8B",
    num_workers: int = 1,
    max_iterations: int = 100,
    eval_limit: int = 500,
    dataset: str = "princeton-nlp/SWE-bench_Verified",
    openhands_model_config: str = "llm.eval_qwen3_8b",
    vllm_extra_flags: list[str] | None = None,
) -> str:
    """Combined serve + infer script.

    Starts vLLM in background, polls until ready (curl health check),
    runs OpenHands inference, then stops the vLLM server.

    Returns script content string.
    """
    bundle_dir = Path(bundle_dir)
    swe_lego_root = "${ACT_SWE_LEGO_ROOT:-" + shlex.quote(str(SWE_LEGO_ROOT)) + "}"
    extra_flags = ""
    if vllm_extra_flags:
        extra_flags = " \\\n    " + " \\\n    ".join(vllm_extra_flags)
    return f"""\
#!/usr/bin/env bash
set -euo pipefail

# Combined serve + infer script — generated by auto-coder-trainer
# Checkpoint: {checkpoint_path}

SWE_LEGO_ROOT={swe_lego_root}
CHECKPOINT_PATH={_shell_quote(checkpoint_path)}
PORT={port}
VLLM_PID=""

cleanup() {{
    if [ -n "$VLLM_PID" ] && kill -0 "$VLLM_PID" 2>/dev/null; then
        echo "Stopping vLLM server (PID=$VLLM_PID)..."
        kill "$VLLM_PID"
        wait "$VLLM_PID" 2>/dev/null || true
    fi
}}
trap cleanup EXIT

# --- Start vLLM in background ---
echo "Starting vLLM server on port $PORT..."
python -m vllm.entrypoints.openai.api_server \\
    --model "$CHECKPOINT_PATH" \\
    --served-model-name "$CHECKPOINT_PATH" \\
    --host 0.0.0.0 \\
    --port "$PORT" \\
    --tensor-parallel-size {tp_size} \\
    --gpu-memory-utilization {gpu_memory_utilization} \\
    --max-model-len {max_model_len} \\
    --max-num-seqs 24 \\
    --api-key "dummy-key"{extra_flags} &
VLLM_PID=$!

# --- Wait for vLLM to become ready ---
echo "Waiting for vLLM server to be ready..."
MAX_WAIT=600
ELAPSED=0
until curl -sf "http://localhost:$PORT/health" > /dev/null 2>&1; do
    if ! kill -0 "$VLLM_PID" 2>/dev/null; then
        echo "ERROR: vLLM process exited unexpectedly."
        exit 1
    fi
    if [ "$ELAPSED" -ge "$MAX_WAIT" ]; then
        echo "ERROR: vLLM server did not become ready within ${{MAX_WAIT}}s."
        exit 1
    fi
    sleep 5
    ELAPSED=$((ELAPSED + 5))
done
echo "vLLM server is ready (took ~${{ELAPSED}}s)."

# --- Run OpenHands inference ---
cd "$SWE_LEGO_ROOT/OpenHands-0.53.0"

MODEL_CONFIG={openhands_model_config}
GIT_VERSION=HEAD
AGENT=CodeActAgent
EVAL_LIMIT={eval_limit}
MAX_ITER={max_iterations}
NUM_WORKERS={num_workers}
DATASET={shlex.quote(dataset)}
DATASET_SPLIT=test
N_RUNS=1
MODE=swe

export USE_HINT_TEXT=false
export INSTRUCTION_TEMPLATE_NAME=swe_default.j2
export ENABLE_PLAN_MODE=false
export ADD_IN_CONTEXT_LEARNING_EXAMPLE=false

./evaluation/benchmarks/swe_bench/scripts/run_infer.sh \\
    "$MODEL_CONFIG" "$GIT_VERSION" "$AGENT" "$EVAL_LIMIT" \\
    "$MAX_ITER" "$NUM_WORKERS" "$DATASET" "$DATASET_SPLIT" \\
    "$N_RUNS" "$MODE"

echo "Inference complete. Stopping vLLM server."
# cleanup runs via trap
"""


def write_inference_scripts(
    bundle_dir: str | Path,
    checkpoint_path: str,
    **kwargs: object,
) -> dict[str, str]:
    """Write all inference scripts to ``bundle_dir/scripts/``.

    Returns dict mapping script name to path.
    """
    bundle_dir = Path(bundle_dir)
    scripts_dir = bundle_dir / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)

    scripts = {
        "serve_vllm.sh": build_serve_script(checkpoint_path, bundle_dir, **{
            k: v for k, v in kwargs.items()
            if k in ("tp_size", "port", "gpu_memory_utilization", "max_model_len")
        }),
        "infer.sh": build_infer_script(bundle_dir, **{
            k: v for k, v in kwargs.items()
            if k in ("model_name", "port", "num_workers", "max_iterations", "eval_limit", "dataset")
        }),
        "eval.sh": build_eval_script(bundle_dir, **{
            k: v for k, v in kwargs.items()
            if k in ("output_jsonl", "dataset")
        }),
        "serve_and_infer.sh": build_serve_and_infer_script(checkpoint_path, bundle_dir, **kwargs),
    }

    result: dict[str, str] = {}
    for name, content in scripts.items():
        path = scripts_dir / name
        path.write_text(content)
        path.chmod(0o755)
        result[name] = str(path)

    return result
